import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { getPages } from '@/sanity/sanity-utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chimba de Página',
  description: 'Generated by create next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Get all of our pages and their slugs
  const pages = await getPages()

  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-5xl mx-auto my-10 `}>
        <header
          className="flex items-center justify-between mt-10 mb-16 space-y-4"
        >
          <Link
            href="/"
            className='bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-4xl font-extrabold drop-shadow-xl'
          >
            Inhumanity
          </Link>

          <div
            className="flex items-center justify-between space-x-4"
          >
            {pages.map((page) => (
              <>
                <Link 

                href={`/${page.slug}`} 
                key={page._id}
                className='hover:text-gray-900 border-b-2 border-transparent hover:border-gray-900'
                >
                  {page.title}
                </Link>
              </>
            ))}
          </div >



        </header>
        <main
          className="mt-10 text-gray-600 prose prose-lg max-w-none"
        >

          {children}
        </main>
      </body>
    </html>
  )
}
